### ISSUE TITLE
Getting NoSuchmethodError: "TTFReader.loadTTF"  after updating BIRT runtime 4.10 to 4.15

### ISSUE THREAD

**Issue by LeonardoIPM** [eclipse-birt/birt#1709]
We are updating our application to BIRT runtime 4.15, but when we run a report in the new version, we get the following error:

```
NoSuchMethodError: 'org.apache.fop.fonts.truetype.TTFFile org.apache.fop.fonts.apps.TTFReader.loadTTF(String, String, boolean, boolean).
 at com.lowagie.text.pdf.TTFCache.loadTTF
 at org.eclipse.birt.report.engine.emitter.pdf.PDFPage.drawText(PDFPage.java:514)
```

I removed the lowagie.text lib, as you switched to OpenPdf.
I'm using OpenPdf 1.4.1, is this the correct lib? I need another dependency? Or any of our lib is giving conflict?

**Comment by LeonardoIPM** [comment]
Never mind, it was a conflict with apache.batik.pdf_1.6.0.jar
